steps:
  # Paso 2: Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-repo-name/your-image-name', '.']

  # Paso 3: Etiquetar la imagen para Artifact Registry
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['tag', 'gcr.io/$PROJECT_ID/your-image-name', 'eu.artifacts.$PROJECT_ID/your-repo-name/your-image-name:latest']

  # Paso 4: Subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-repo-name/your-image-name']



# steps:
#   # Construir la imagen de Docker
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/your-repo-name/your-image-name:latest', '.']
#   # Autenticar para Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['--', 'login', '-u', 'oauth2accesstoken', '-p', '$(gcloud auth print-access-token)', 'https://us-central1-docker.pkg.dev']
#   # Subir la imagen de Docker a Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/your-repo-name/your-image-name:latest']


